# Generated by Django 3.0.5 on 2020-04-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'Armée',
                'verbose_name_plural': 'Armées',
                'default_related_name': 'army',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('order', models.PositiveIntegerField(verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
                'ordering': ['order'],
                'default_related_name': 'game',
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='A')),
                ('unit_type_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_type', to='minis.UnitType', verbose_name="type d'unité parent")),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['name'],
                'default_related_name': 'unit_type',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Sur grappe'), (1, 'Assemblage'), (2, 'Sous couché'), (3, 'Peinture en cours'), (4, 'Soclage'), (4, 'Terminé')], default=0, verbose_name='état')),
                ('number_of_minis', models.PositiveIntegerField(default=1, verbose_name="nombre de figurines de l'unité")),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='minis.Army', verbose_name='armée')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='minis.UnitType', verbose_name="type d'unité")),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['army', 'state', 'name'],
                'default_related_name': 'unit',
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('order', models.PositiveIntegerField(verbose_name='ordre')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faction', to='minis.Game', verbose_name='jeu')),
            ],
            options={
                'verbose_name': 'Faction',
                'verbose_name_plural': 'Factions',
                'ordering': ['order'],
                'default_related_name': 'faction',
            },
        ),
        migrations.AddField(
            model_name='army',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='army', to='minis.Faction', verbose_name='faction'),
        ),
    ]
